Django overhaul
architect-templates/django pull request #12
Opened 2022-09-20 22:38 UTC by Zach-at-Arch

## Overview
Re-creating Django app using the Movie app template from react/node.

## Changes
- Removing `Polls` app
- Creating `Movies` app
- Updating `architectexample` folder to seamlessly use the app

## Pictures
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/102044904/191377307-656c6f8f-beb7-4608-89fc-411a5f27a2b1.png">

## TODO List
Before merging, a PR will need
- [ ] Signoff from product if there are UX changes 
- [ ] Signoff from one other engineer at Architect.io

2022-10-03 14:30 UTC, TylerAldrich requested changes

2022-10-03 14:30 UTC, TylerAldrich commented on README.md
> +In this example, you'll learn how to capture an API written with [django](https://www.djangoproject.com/) with a [Postgre](https://www.postgresql.org/)
should either be `Postgres` or `PostgreSQL`

2022-10-03 14:30 UTC, TylerAldrich commented on README.md
> +You can then [deploy the component](https://docs.architect.io/getting-started/introduction/#deploy-to-the-cloud) using the command below from the `flask` directory. Note that “example-environment” is
Says `flask` directory  - i think this would be run from the root directory? Definitely not flask though 😛

2022-10-03 14:30 UTC, TylerAldrich commented on architectexample/views.py
> +  return HttpResponse("<H1>Architect Movie App</H1>")
Not a big deal but the capitalized `<H1>` that was here before seems weird - I assume it's technically valid html but i've never seen it not lowercase

2022-10-03 14:30 UTC, TylerAldrich commented on movies/views.py
> +    rating = request.POST['forRating']
is this supposed to be `'formRating'`?

2022-10-03 14:30 UTC, TylerAldrich commented on static/movies/style.css
> +html {
I can't tell if this is exactly the same as the `static/style.css` but they look almost identical, are both necessary? I'd assume `static/style.css` has the 'core' styles and we'd only use this file if there was some small overrides, but wouldn't expect to re-style `html`, `body`, etc here

2022-11-01 21:00 UTC, Zach-at-Arch commented
Closing this PR in favor of the new one - https://github.com/architect-templates/django/pull/14

The new PR is a template for more full-stack/monolith applications and will be used for other frameworks as a reference

2022-11-01 21:00 UTC, closed without merging